<a href="https://colab.research.google.com/github/MarcosRolando/OrgaDeDatosTP2/blob/main/neuralNetwoork.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
import pandas as pd
import numpy as np
from tensorflow import keras
from tensorflow.keras import layers


In [ ]:
df = pd.read_csv('/content/Train_TP2_Datos_2020-2C.csv')
df = df[df['Stage'].isin(['Closed Won', 'Closed Lost'])]
df.loc[:, 'Stage'].replace({'Closed Won':1, 'Closed Lost':0}, inplace=True)
results = df['Stage'].to_numpy()
input = df['ASP_(converted)'].to_numpy()

In [ ]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [ ]:
model = tf.keras.models.Sequential([
  #tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Flatten(input_shape=(1,1)),
  tf.keras.layers.Dense(128, activation='relu'), #la funcion Dense genera una capa de neuronas nueva, en este caso de 128 neuronas con funcion de activacion ReLu
  tf.keras.layers.Dropout(0.2), #la funcion Dropout especifica el rate de desactivacion de las neuronas, en este caso desactiva el 20% de las neuronas para evitar que se genere overfitting
  tf.keras.layers.Dense(2) #output layer (not hidden)
])

In [ ]:
#predictions = model(x_train[:1]).numpy()
predictions = model(input).numpy()
predictions

array([[0.0340301 , 0.03820564],
       [0.03468448, 0.03894031],
       [0.02777164, 0.03117925],
       ...,
       [0.0340301 , 0.03820564],
       [0.03688423, 0.04140997],
       [0.03702886, 0.04157235]], dtype=float32)

In [ ]:
tf.nn.softmax(predictions).numpy()

array([[0.49895608, 0.50104386],
       [0.49893603, 0.50106394],
       [0.49914807, 0.50085187],
       ...,
       [0.49895608, 0.50104386],
       [0.49886855, 0.5011314 ],
       [0.49886414, 0.5011359 ]], dtype=float32)

In [ ]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True) #aca definimos la funcion de loss, no es la nuestra la de esta linea asi que hay que MODIFICARLO PARA QUE SEA LA DEL TP

In [ ]:
#loss_fn(y_train[:1], predictions).numpy()
loss_fn(results[1], predictions[1]).numpy() #esto calcula para cada elemento (el indice especifica cual de los 16800 no se cuantos elementos queres calcularle el loss)

0.69102156

In [ ]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [ ]:
#model.fit(x_train, y_train, epochs=5)
model.fit(input, results, epochs=10)

Epoch 1/10
528/528 [==============================] - 1s 2ms/step - loss: 0.6931 - accuracy: 0.5638
Epoch 2/10
528/528 [==============================] - 1s 2ms/step - loss: 0.6931 - accuracy: 0.5661
Epoch 3/10
528/528 [==============================] - 1s 2ms/step - loss: 0.6930 - accuracy: 0.5671
Epoch 4/10
528/528 [==============================] - 1s 2ms/step - loss: 0.6930 - accuracy: 0.5592
Epoch 5/10
528/528 [==============================] - 1s 2ms/step - loss: 0.6930 - accuracy: 0.5576
Epoch 6/10
528/528 [==============================] - 1s 2ms/step - loss: 0.6929 - accuracy: 0.5703
Epoch 7/10
528/528 [==============================] - 1s 2ms/step - loss: 0.6929 - accuracy: 0.5602
Epoch 8/10
528/528 [==============================] - 1s 2ms/step - loss: 0.6928 - accuracy: 0.5632
Epoch 9/10
528/528 [==============================] - 1s 2ms/step - loss: 0.6928 - accuracy: 0.5645
Epoch 10/10
528/528 [==============================] - 1s 2ms/step - loss: 0.6927 - accuracy: 0.5681

In [ ]:
#model.evaluate(x_test,  y_test, verbose=2)
model.evaluate(input,  results, verbose=2)

528/528 - 1s - loss: 0.6927 - accuracy: 0.5647


[0.6926782131195068, 0.56465083360672]

In [ ]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [ ]:
#probability_model(x_test[:5])
probability_model(results)

<tf.Tensor: shape=(16883, 2), dtype=float32, numpy=
array([[0.4981607 , 0.50183934],
       [0.4981607 , 0.50183934],
       [0.4981607 , 0.50183934],
       ...,
       [0.4981607 , 0.50183934],
       [0.4981607 , 0.50183934],
       [0.4981607 , 0.50183934]], dtype=float32)>